# Generated by Django 4.0.3 on 2022-04-19 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SNA', '0002_alter_dataset_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_datetime', models.DateTimeField(verbose_name='date execute')),
                ('alg_name', models.CharField(max_length=200)),
                ('task_name', models.CharField(max_length=200)),
                ('dataset_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SNA.dataset')),
            ],
        ),
    ]
