# Generated by Django 4.0.3 on 2022-04-28 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SNA', '0006_dataset_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='runresult',
            name='exec_er',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
