# Generated by Django 4.0.3 on 2022-04-28 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SNA', '0007_runresult_exec_er'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runresult',
            name='exec_er',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
